name: Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SBanditaDas
          template: classic
          base: activity
          config_timezone: Asia/Kolkata

          
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic

         
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

         
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, contributor
          plugin_repositories_pinned: 3

          
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 6
          plugin_languages_sections: most-used

          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.METRICS_TOKEN }}
